package com.winston.mapper;

import com.winston.entity.ProGroup;
import com.winston.entity.ProGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    long countByExample(ProGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int deleteByExample(ProGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int insert(ProGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int insertSelective(ProGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    List<ProGroup> selectByExample(ProGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    ProGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProGroup record, @Param("example") ProGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProGroup record, @Param("example") ProGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProGroup record);
}