package com.winston.entity;

import java.io.Serializable;

public class ProjectLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.problem
     *
     * @mbg.generated
     */
    private String problem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.create_opr
     *
     * @mbg.generated
     */
    private String createOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_log.update_opr
     *
     * @mbg.generated
     */
    private String updateOpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.id
     *
     * @return the value of project_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.id
     *
     * @param id the value for project_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.project_id
     *
     * @return the value of project_log.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.project_id
     *
     * @param projectId the value for project_log.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.staff_id
     *
     * @return the value of project_log.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.staff_id
     *
     * @param staffId the value for project_log.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.problem
     *
     * @return the value of project_log.problem
     *
     * @mbg.generated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.problem
     *
     * @param problem the value for project_log.problem
     *
     * @mbg.generated
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.status
     *
     * @return the value of project_log.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.status
     *
     * @param status the value for project_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.create_time
     *
     * @return the value of project_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.create_time
     *
     * @param createTime the value for project_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.create_opr
     *
     * @return the value of project_log.create_opr
     *
     * @mbg.generated
     */
    public String getCreateOpr() {
        return createOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.create_opr
     *
     * @param createOpr the value for project_log.create_opr
     *
     * @mbg.generated
     */
    public void setCreateOpr(String createOpr) {
        this.createOpr = createOpr == null ? null : createOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.update_time
     *
     * @return the value of project_log.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.update_time
     *
     * @param updateTime the value for project_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_log.update_opr
     *
     * @return the value of project_log.update_opr
     *
     * @mbg.generated
     */
    public String getUpdateOpr() {
        return updateOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_log.update_opr
     *
     * @param updateOpr the value for project_log.update_opr
     *
     * @mbg.generated
     */
    public void setUpdateOpr(String updateOpr) {
        this.updateOpr = updateOpr == null ? null : updateOpr.trim();
    }
}