package com.winston.entity;

import java.io.Serializable;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_name
     *
     * @mbg.generated
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rel_end_time
     *
     * @mbg.generated
     */
    private Long relEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.over_time_desc
     *
     * @mbg.generated
     */
    private String overTimeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.schedule
     *
     * @mbg.generated
     */
    private String schedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.client_status
     *
     * @mbg.generated
     */
    private Integer clientStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.staff_status
     *
     * @mbg.generated
     */
    private Integer staffStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_opr
     *
     * @mbg.generated
     */
    private String createOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_opr
     *
     * @mbg.generated
     */
    private String updateOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pro_desc
     *
     * @mbg.generated
     */
    private String proDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pro_name
     *
     * @return the value of project.pro_name
     *
     * @mbg.generated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pro_name
     *
     * @param proName the value for project.pro_name
     *
     * @mbg.generated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.start_time
     *
     * @return the value of project.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.start_time
     *
     * @param startTime the value for project.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_time
     *
     * @return the value of project.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_time
     *
     * @param endTime the value for project.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rel_end_time
     *
     * @return the value of project.rel_end_time
     *
     * @mbg.generated
     */
    public Long getRelEndTime() {
        return relEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rel_end_time
     *
     * @param relEndTime the value for project.rel_end_time
     *
     * @mbg.generated
     */
    public void setRelEndTime(Long relEndTime) {
        this.relEndTime = relEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.over_time_desc
     *
     * @return the value of project.over_time_desc
     *
     * @mbg.generated
     */
    public String getOverTimeDesc() {
        return overTimeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.over_time_desc
     *
     * @param overTimeDesc the value for project.over_time_desc
     *
     * @mbg.generated
     */
    public void setOverTimeDesc(String overTimeDesc) {
        this.overTimeDesc = overTimeDesc == null ? null : overTimeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.schedule
     *
     * @return the value of project.schedule
     *
     * @mbg.generated
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.schedule
     *
     * @param schedule the value for project.schedule
     *
     * @mbg.generated
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule == null ? null : schedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.parent_id
     *
     * @return the value of project.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.parent_id
     *
     * @param parentId the value for project.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.client_status
     *
     * @return the value of project.client_status
     *
     * @mbg.generated
     */
    public Integer getClientStatus() {
        return clientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.client_status
     *
     * @param clientStatus the value for project.client_status
     *
     * @mbg.generated
     */
    public void setClientStatus(Integer clientStatus) {
        this.clientStatus = clientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.staff_status
     *
     * @return the value of project.staff_status
     *
     * @mbg.generated
     */
    public Integer getStaffStatus() {
        return staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.staff_status
     *
     * @param staffStatus the value for project.staff_status
     *
     * @mbg.generated
     */
    public void setStaffStatus(Integer staffStatus) {
        this.staffStatus = staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_opr
     *
     * @return the value of project.create_opr
     *
     * @mbg.generated
     */
    public String getCreateOpr() {
        return createOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_opr
     *
     * @param createOpr the value for project.create_opr
     *
     * @mbg.generated
     */
    public void setCreateOpr(String createOpr) {
        this.createOpr = createOpr == null ? null : createOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_opr
     *
     * @return the value of project.update_opr
     *
     * @mbg.generated
     */
    public String getUpdateOpr() {
        return updateOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_opr
     *
     * @param updateOpr the value for project.update_opr
     *
     * @mbg.generated
     */
    public void setUpdateOpr(String updateOpr) {
        this.updateOpr = updateOpr == null ? null : updateOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pro_desc
     *
     * @return the value of project.pro_desc
     *
     * @mbg.generated
     */
    public String getProDesc() {
        return proDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pro_desc
     *
     * @param proDesc the value for project.pro_desc
     *
     * @mbg.generated
     */
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc == null ? null : proDesc.trim();
    }
}